- name: Portfolio setup
  hosts: all
  become: yes
  tasks:
    - name: Install Java 21
      ansible.builtin.dnf:
        name: "@java:21"
        state: present

    - name: Adding appuser & creating directory
      ansible.builtin.shell: useradd -r -s /bin/false appuser ; mkdir - p /app

    - name: Downloading and extracting portfolio artifacts
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/portfolio-service.tar.gz
        dest: /app
        remoste:src: yes

    - name: Updating portfolio-service.service file
      ansible.builtin.copy:
        src: portfolio-service.service
        dest: /etc/systemd/system/portfolio-service.service

    - name: change owner and modification.
      ansible.builtin.shell: cd /app ; chmod +x gradlew ; ./gradlew bootJar --no-daemon -x test

    - name: Daemon reload
      ansible.builtin.shell: systemctl daemon-reload

    - name: starting portfolio-service
      ansible.builtin.systemd:
        name: portfolio-service
        state: restarted
        enabled: yes
